services:
  broker-service:
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/broker-service.dockerfile
    restart: always
    ports:
      - "8080:8080" 
    deploy:
      mode: replicated
      replicas: 1

  auth-service:
    build:
      context: ./../auth-service
      dockerfile: ./../auth-service/auth-service.dockerfile
    restart: always
    ports:
      - "8081:80" 
    deploy:
      mode: replicated
      replicas: 1

  listener-service:
    build:
      context: ./../listener-service
      dockerfile: ./../listener-service/listener-service.dockerfile
    deploy:
      mode: replicated
      replicas: 1

  redis:
    image: 'redis:7.2.5-alpine'
    restart: always
    ports:
      - "6379:6379" 
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - ./data:/data
