// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: routine.proto

package routine

import (
	model "github.com/flavioesteves/wizer-app/broker/proto/model"
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRoutineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Routine *model.Routine `protobuf:"bytes,1,opt,name=routine,proto3" json:"routine,omitempty"`
}

func (x *CreateRoutineRequest) Reset() {
	*x = CreateRoutineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_routine_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoutineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoutineRequest) ProtoMessage() {}

func (x *CreateRoutineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routine_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoutineRequest.ProtoReflect.Descriptor instead.
func (*CreateRoutineRequest) Descriptor() ([]byte, []int) {
	return file_routine_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRoutineRequest) GetRoutine() *model.Routine {
	if x != nil {
		return x.Routine
	}
	return nil
}

type GetRoutineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetRoutineRequest) Reset() {
	*x = GetRoutineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_routine_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRoutineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoutineRequest) ProtoMessage() {}

func (x *GetRoutineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routine_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoutineRequest.ProtoReflect.Descriptor instead.
func (*GetRoutineRequest) Descriptor() ([]byte, []int) {
	return file_routine_proto_rawDescGZIP(), []int{1}
}

func (x *GetRoutineRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateRoutineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Routine *model.Routine `protobuf:"bytes,1,opt,name=routine,proto3" json:"routine,omitempty"`
}

func (x *UpdateRoutineRequest) Reset() {
	*x = UpdateRoutineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_routine_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRoutineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoutineRequest) ProtoMessage() {}

func (x *UpdateRoutineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routine_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoutineRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoutineRequest) Descriptor() ([]byte, []int) {
	return file_routine_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateRoutineRequest) GetRoutine() *model.Routine {
	if x != nil {
		return x.Routine
	}
	return nil
}

type DeleteRoutineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteRoutineRequest) Reset() {
	*x = DeleteRoutineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_routine_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRoutineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoutineRequest) ProtoMessage() {}

func (x *DeleteRoutineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routine_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoutineRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoutineRequest) Descriptor() ([]byte, []int) {
	return file_routine_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteRoutineRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAllRoutinesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllRoutinesRequest) Reset() {
	*x = GetAllRoutinesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_routine_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllRoutinesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRoutinesRequest) ProtoMessage() {}

func (x *GetAllRoutinesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routine_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRoutinesRequest.ProtoReflect.Descriptor instead.
func (*GetAllRoutinesRequest) Descriptor() ([]byte, []int) {
	return file_routine_proto_rawDescGZIP(), []int{4}
}

type GetAllRoutinesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Routines []*model.Routine `protobuf:"bytes,1,rep,name=routines,proto3" json:"routines,omitempty"`
}

func (x *GetAllRoutinesResponse) Reset() {
	*x = GetAllRoutinesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_routine_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllRoutinesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRoutinesResponse) ProtoMessage() {}

func (x *GetAllRoutinesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_routine_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRoutinesResponse.ProtoReflect.Descriptor instead.
func (*GetAllRoutinesResponse) Descriptor() ([]byte, []int) {
	return file_routine_proto_rawDescGZIP(), []int{5}
}

func (x *GetAllRoutinesResponse) GetRoutines() []*model.Routine {
	if x != nil {
		return x.Routines
	}
	return nil
}

type RoutineResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Routine *model.Routine `protobuf:"bytes,1,opt,name=routine,proto3" json:"routine,omitempty"`
}

func (x *RoutineResponse) Reset() {
	*x = RoutineResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_routine_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoutineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutineResponse) ProtoMessage() {}

func (x *RoutineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_routine_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutineResponse.ProtoReflect.Descriptor instead.
func (*RoutineResponse) Descriptor() ([]byte, []int) {
	return file_routine_proto_rawDescGZIP(), []int{6}
}

func (x *RoutineResponse) GetRoutine() *model.Routine {
	if x != nil {
		return x.Routine
	}
	return nil
}

// Relationship many to many Routine <-> Exercise
type AddExerciseToRoutineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoutineId   string   `protobuf:"bytes,1,opt,name=routine_id,json=routineId,proto3" json:"routine_id,omitempty"`
	ExerciseIds []string `protobuf:"bytes,2,rep,name=exercise_ids,json=exerciseIds,proto3" json:"exercise_ids,omitempty"`
}

func (x *AddExerciseToRoutineRequest) Reset() {
	*x = AddExerciseToRoutineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_routine_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddExerciseToRoutineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddExerciseToRoutineRequest) ProtoMessage() {}

func (x *AddExerciseToRoutineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routine_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddExerciseToRoutineRequest.ProtoReflect.Descriptor instead.
func (*AddExerciseToRoutineRequest) Descriptor() ([]byte, []int) {
	return file_routine_proto_rawDescGZIP(), []int{7}
}

func (x *AddExerciseToRoutineRequest) GetRoutineId() string {
	if x != nil {
		return x.RoutineId
	}
	return ""
}

func (x *AddExerciseToRoutineRequest) GetExerciseIds() []string {
	if x != nil {
		return x.ExerciseIds
	}
	return nil
}

type AddExerciseToRoutineResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *AddExerciseToRoutineResponse) Reset() {
	*x = AddExerciseToRoutineResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_routine_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddExerciseToRoutineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddExerciseToRoutineResponse) ProtoMessage() {}

func (x *AddExerciseToRoutineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_routine_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddExerciseToRoutineResponse.ProtoReflect.Descriptor instead.
func (*AddExerciseToRoutineResponse) Descriptor() ([]byte, []int) {
	return file_routine_proto_rawDescGZIP(), []int{8}
}

func (x *AddExerciseToRoutineResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RemoveExerciseFromRoutineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoutineId   string   `protobuf:"bytes,1,opt,name=routine_id,json=routineId,proto3" json:"routine_id,omitempty"`
	ExerciseIds []string `protobuf:"bytes,2,rep,name=exercise_ids,json=exerciseIds,proto3" json:"exercise_ids,omitempty"`
}

func (x *RemoveExerciseFromRoutineRequest) Reset() {
	*x = RemoveExerciseFromRoutineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_routine_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveExerciseFromRoutineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveExerciseFromRoutineRequest) ProtoMessage() {}

func (x *RemoveExerciseFromRoutineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routine_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveExerciseFromRoutineRequest.ProtoReflect.Descriptor instead.
func (*RemoveExerciseFromRoutineRequest) Descriptor() ([]byte, []int) {
	return file_routine_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveExerciseFromRoutineRequest) GetRoutineId() string {
	if x != nil {
		return x.RoutineId
	}
	return ""
}

func (x *RemoveExerciseFromRoutineRequest) GetExerciseIds() []string {
	if x != nil {
		return x.ExerciseIds
	}
	return nil
}

type RemoveExerciseFromRoutineResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *RemoveExerciseFromRoutineResponse) Reset() {
	*x = RemoveExerciseFromRoutineResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_routine_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveExerciseFromRoutineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveExerciseFromRoutineResponse) ProtoMessage() {}

func (x *RemoveExerciseFromRoutineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_routine_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveExerciseFromRoutineResponse.ProtoReflect.Descriptor instead.
func (*RemoveExerciseFromRoutineResponse) Descriptor() ([]byte, []int) {
	return file_routine_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveExerciseFromRoutineResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetExercisesByRoutineIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoutineId string `protobuf:"bytes,1,opt,name=routine_id,json=routineId,proto3" json:"routine_id,omitempty"`
}

func (x *GetExercisesByRoutineIdRequest) Reset() {
	*x = GetExercisesByRoutineIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_routine_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetExercisesByRoutineIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExercisesByRoutineIdRequest) ProtoMessage() {}

func (x *GetExercisesByRoutineIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routine_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExercisesByRoutineIdRequest.ProtoReflect.Descriptor instead.
func (*GetExercisesByRoutineIdRequest) Descriptor() ([]byte, []int) {
	return file_routine_proto_rawDescGZIP(), []int{11}
}

func (x *GetExercisesByRoutineIdRequest) GetRoutineId() string {
	if x != nil {
		return x.RoutineId
	}
	return ""
}

type GetExercisesByRoutineIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exercises []*model.Exercise `protobuf:"bytes,1,rep,name=exercises,proto3" json:"exercises,omitempty"`
}

func (x *GetExercisesByRoutineIdResponse) Reset() {
	*x = GetExercisesByRoutineIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_routine_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetExercisesByRoutineIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExercisesByRoutineIdResponse) ProtoMessage() {}

func (x *GetExercisesByRoutineIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_routine_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExercisesByRoutineIdResponse.ProtoReflect.Descriptor instead.
func (*GetExercisesByRoutineIdResponse) Descriptor() ([]byte, []int) {
	return file_routine_proto_rawDescGZIP(), []int{12}
}

func (x *GetExercisesByRoutineIdResponse) GetExercises() []*model.Exercise {
	if x != nil {
		return x.Exercises
	}
	return nil
}

var File_routine_proto protoreflect.FileDescriptor

var file_routine_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0b, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x40, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x75, 0x74,
	0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x07, 0x72, 0x6f,
	0x75, 0x74, 0x69, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x52, 0x07, 0x72, 0x6f, 0x75,
	0x74, 0x69, 0x6e, 0x65, 0x22, 0x23, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x75, 0x74, 0x69,
	0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x40, 0x0a, 0x14, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x28, 0x0a, 0x07, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x69,
	0x6e, 0x65, 0x52, 0x07, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x22, 0x26, 0x0a, 0x14, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x17, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x6f, 0x75,
	0x74, 0x69, 0x6e, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x44, 0x0a, 0x16,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x08, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2e, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x52, 0x08, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e,
	0x65, 0x73, 0x22, 0x3b, 0x0a, 0x0f, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x52,
	0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x52, 0x07, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x22,
	0x5f, 0x0a, 0x1b, 0x41, 0x64, 0x64, 0x45, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x54, 0x6f,
	0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x21, 0x0a,
	0x0c, 0x65, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x49, 0x64, 0x73,
	0x22, 0x38, 0x0a, 0x1c, 0x41, 0x64, 0x64, 0x45, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x54,
	0x6f, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x64, 0x0a, 0x20, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x45, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x46, 0x72, 0x6f, 0x6d,
	0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x21, 0x0a,
	0x0c, 0x65, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x49, 0x64, 0x73,
	0x22, 0x3d, 0x0a, 0x21, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x45, 0x78, 0x65, 0x72, 0x63, 0x69,
	0x73, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22,
	0x3f, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x45, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x73, 0x42,
	0x79, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x49, 0x64,
	0x22, 0x50, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x45, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x73,
	0x42, 0x79, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x09, 0x65, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x45,
	0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x52, 0x09, 0x65, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73,
	0x65, 0x73, 0x32, 0xca, 0x05, 0x0a, 0x0e, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x48, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x12, 0x1d, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x2e,
	0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x42, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x12, 0x1a, 0x2e,
	0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x75, 0x74, 0x69,
	0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x72, 0x6f, 0x75, 0x74,
	0x69, 0x6e, 0x65, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x75,
	0x74, 0x69, 0x6e, 0x65, 0x12, 0x1d, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x2e, 0x52, 0x6f,
	0x75, 0x74, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a,
	0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x12, 0x1d,
	0x2e, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x51, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52,
	0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x73, 0x12, 0x1e, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e,
	0x65, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e,
	0x65, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x63, 0x0a, 0x14, 0x41, 0x64, 0x64, 0x45,
	0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x54, 0x6f, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65,
	0x12, 0x24, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x45, 0x78,
	0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x54, 0x6f, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65,
	0x2e, 0x41, 0x64, 0x64, 0x45, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x54, 0x6f, 0x52, 0x6f,
	0x75, 0x74, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x72, 0x0a,
	0x19, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x45, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x46,
	0x72, 0x6f, 0x6d, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x12, 0x29, 0x2e, 0x72, 0x6f, 0x75,
	0x74, 0x69, 0x6e, 0x65, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x45, 0x78, 0x65, 0x72, 0x63,
	0x69, 0x73, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x2e,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x45, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x46, 0x72,
	0x6f, 0x6d, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x6c, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x45, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65,
	0x73, 0x42, 0x79, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x27, 0x2e, 0x72,
	0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x78, 0x65, 0x72, 0x63, 0x69,
	0x73, 0x65, 0x73, 0x42, 0x79, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x2e,
	0x47, 0x65, 0x74, 0x45, 0x78, 0x65, 0x72, 0x63, 0x69, 0x73, 0x65, 0x73, 0x42, 0x79, 0x52, 0x6f,
	0x75, 0x74, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x6c,
	0x61, 0x76, 0x69, 0x6f, 0x65, 0x73, 0x74, 0x65, 0x76, 0x65, 0x73, 0x2f, 0x77, 0x69, 0x7a, 0x65,
	0x72, 0x2d, 0x61, 0x70, 0x70, 0x2f, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_routine_proto_rawDescOnce sync.Once
	file_routine_proto_rawDescData = file_routine_proto_rawDesc
)

func file_routine_proto_rawDescGZIP() []byte {
	file_routine_proto_rawDescOnce.Do(func() {
		file_routine_proto_rawDescData = protoimpl.X.CompressGZIP(file_routine_proto_rawDescData)
	})
	return file_routine_proto_rawDescData
}

var file_routine_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_routine_proto_goTypes = []any{
	(*CreateRoutineRequest)(nil),              // 0: routine.CreateRoutineRequest
	(*GetRoutineRequest)(nil),                 // 1: routine.GetRoutineRequest
	(*UpdateRoutineRequest)(nil),              // 2: routine.UpdateRoutineRequest
	(*DeleteRoutineRequest)(nil),              // 3: routine.DeleteRoutineRequest
	(*GetAllRoutinesRequest)(nil),             // 4: routine.GetAllRoutinesRequest
	(*GetAllRoutinesResponse)(nil),            // 5: routine.GetAllRoutinesResponse
	(*RoutineResponse)(nil),                   // 6: routine.RoutineResponse
	(*AddExerciseToRoutineRequest)(nil),       // 7: routine.AddExerciseToRoutineRequest
	(*AddExerciseToRoutineResponse)(nil),      // 8: routine.AddExerciseToRoutineResponse
	(*RemoveExerciseFromRoutineRequest)(nil),  // 9: routine.RemoveExerciseFromRoutineRequest
	(*RemoveExerciseFromRoutineResponse)(nil), // 10: routine.RemoveExerciseFromRoutineResponse
	(*GetExercisesByRoutineIdRequest)(nil),    // 11: routine.GetExercisesByRoutineIdRequest
	(*GetExercisesByRoutineIdResponse)(nil),   // 12: routine.GetExercisesByRoutineIdResponse
	(*model.Routine)(nil),                     // 13: model.Routine
	(*model.Exercise)(nil),                    // 14: model.Exercise
	(*empty.Empty)(nil),                       // 15: google.protobuf.Empty
}
var file_routine_proto_depIdxs = []int32{
	13, // 0: routine.CreateRoutineRequest.routine:type_name -> model.Routine
	13, // 1: routine.UpdateRoutineRequest.routine:type_name -> model.Routine
	13, // 2: routine.GetAllRoutinesResponse.routines:type_name -> model.Routine
	13, // 3: routine.RoutineResponse.routine:type_name -> model.Routine
	14, // 4: routine.GetExercisesByRoutineIdResponse.exercises:type_name -> model.Exercise
	0,  // 5: routine.RoutineService.CreateRoutine:input_type -> routine.CreateRoutineRequest
	1,  // 6: routine.RoutineService.GetRoutine:input_type -> routine.GetRoutineRequest
	2,  // 7: routine.RoutineService.UpdateRoutine:input_type -> routine.UpdateRoutineRequest
	3,  // 8: routine.RoutineService.DeleteRoutine:input_type -> routine.DeleteRoutineRequest
	4,  // 9: routine.RoutineService.GetAllRoutines:input_type -> routine.GetAllRoutinesRequest
	7,  // 10: routine.RoutineService.AddExerciseToRoutine:input_type -> routine.AddExerciseToRoutineRequest
	9,  // 11: routine.RoutineService.RemoveExerciseFromRoutine:input_type -> routine.RemoveExerciseFromRoutineRequest
	11, // 12: routine.RoutineService.GetExercisesByRoutineId:input_type -> routine.GetExercisesByRoutineIdRequest
	6,  // 13: routine.RoutineService.CreateRoutine:output_type -> routine.RoutineResponse
	6,  // 14: routine.RoutineService.GetRoutine:output_type -> routine.RoutineResponse
	6,  // 15: routine.RoutineService.UpdateRoutine:output_type -> routine.RoutineResponse
	15, // 16: routine.RoutineService.DeleteRoutine:output_type -> google.protobuf.Empty
	5,  // 17: routine.RoutineService.GetAllRoutines:output_type -> routine.GetAllRoutinesResponse
	8,  // 18: routine.RoutineService.AddExerciseToRoutine:output_type -> routine.AddExerciseToRoutineResponse
	10, // 19: routine.RoutineService.RemoveExerciseFromRoutine:output_type -> routine.RemoveExerciseFromRoutineResponse
	12, // 20: routine.RoutineService.GetExercisesByRoutineId:output_type -> routine.GetExercisesByRoutineIdResponse
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_routine_proto_init() }
func file_routine_proto_init() {
	if File_routine_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_routine_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CreateRoutineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_routine_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetRoutineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_routine_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateRoutineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_routine_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteRoutineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_routine_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetAllRoutinesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_routine_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetAllRoutinesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_routine_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*RoutineResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_routine_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*AddExerciseToRoutineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_routine_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*AddExerciseToRoutineResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_routine_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*RemoveExerciseFromRoutineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_routine_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*RemoveExerciseFromRoutineResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_routine_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*GetExercisesByRoutineIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_routine_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*GetExercisesByRoutineIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_routine_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_routine_proto_goTypes,
		DependencyIndexes: file_routine_proto_depIdxs,
		MessageInfos:      file_routine_proto_msgTypes,
	}.Build()
	File_routine_proto = out.File
	file_routine_proto_rawDesc = nil
	file_routine_proto_goTypes = nil
	file_routine_proto_depIdxs = nil
}
