// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: rmessage.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data string `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *RMessage) Reset() {
	*x = RMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rmessage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RMessage) ProtoMessage() {}

func (x *RMessage) ProtoReflect() protoreflect.Message {
	mi := &file_rmessage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RMessage.ProtoReflect.Descriptor instead.
func (*RMessage) Descriptor() ([]byte, []int) {
	return file_rmessage_proto_rawDescGZIP(), []int{0}
}

func (x *RMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RMessage) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type RMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RmessageEntry *RMessage `protobuf:"bytes,1,opt,name=rmessageEntry,proto3" json:"rmessageEntry,omitempty"`
}

func (x *RMessageRequest) Reset() {
	*x = RMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rmessage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RMessageRequest) ProtoMessage() {}

func (x *RMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rmessage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RMessageRequest.ProtoReflect.Descriptor instead.
func (*RMessageRequest) Descriptor() ([]byte, []int) {
	return file_rmessage_proto_rawDescGZIP(), []int{1}
}

func (x *RMessageRequest) GetRmessageEntry() *RMessage {
	if x != nil {
		return x.RmessageEntry
	}
	return nil
}

type RMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *RMessageResponse) Reset() {
	*x = RMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rmessage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RMessageResponse) ProtoMessage() {}

func (x *RMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rmessage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RMessageResponse.ProtoReflect.Descriptor instead.
func (*RMessageResponse) Descriptor() ([]byte, []int) {
	return file_rmessage_proto_rawDescGZIP(), []int{2}
}

func (x *RMessageResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_rmessage_proto protoreflect.FileDescriptor

var file_rmessage_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x72, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x72, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x32, 0x0a, 0x08, 0x52, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x4b,
	0x0a, 0x0f, 0x52, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x38, 0x0a, 0x0d, 0x72, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x72, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x52, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x0d, 0x72, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x22, 0x2a, 0x0a, 0x10, 0x52,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x57, 0x0a, 0x0f, 0x52, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x44, 0x0a, 0x0b, 0x53, 0x65,
	0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x19, 0x2e, 0x72, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x72, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x52, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66,
	0x6c, 0x61, 0x76, 0x69, 0x6f, 0x65, 0x73, 0x74, 0x65, 0x76, 0x65, 0x73, 0x2f, 0x77, 0x69, 0x7a,
	0x65, 0x72, 0x2d, 0x61, 0x70, 0x70, 0x2f, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rmessage_proto_rawDescOnce sync.Once
	file_rmessage_proto_rawDescData = file_rmessage_proto_rawDesc
)

func file_rmessage_proto_rawDescGZIP() []byte {
	file_rmessage_proto_rawDescOnce.Do(func() {
		file_rmessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_rmessage_proto_rawDescData)
	})
	return file_rmessage_proto_rawDescData
}

var file_rmessage_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rmessage_proto_goTypes = []any{
	(*RMessage)(nil),         // 0: rmessage.RMessage
	(*RMessageRequest)(nil),  // 1: rmessage.RMessageRequest
	(*RMessageResponse)(nil), // 2: rmessage.RMessageResponse
}
var file_rmessage_proto_depIdxs = []int32{
	0, // 0: rmessage.RMessageRequest.rmessageEntry:type_name -> rmessage.RMessage
	1, // 1: rmessage.RMessageService.SendMessage:input_type -> rmessage.RMessageRequest
	2, // 2: rmessage.RMessageService.SendMessage:output_type -> rmessage.RMessageResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rmessage_proto_init() }
func file_rmessage_proto_init() {
	if File_rmessage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rmessage_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*RMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rmessage_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*RMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rmessage_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*RMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rmessage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rmessage_proto_goTypes,
		DependencyIndexes: file_rmessage_proto_depIdxs,
		MessageInfos:      file_rmessage_proto_msgTypes,
	}.Build()
	File_rmessage_proto = out.File
	file_rmessage_proto_rawDesc = nil
	file_rmessage_proto_goTypes = nil
	file_rmessage_proto_depIdxs = nil
}
